name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
      - name: Install dependencies
        run: composer install
      - name: Check phpstan
        run: composer stan
      - name: Check lint
        run: ./vendor/bin/pint --test
  phpunit:
    strategy:
      matrix:
        php_version: [8.0, 8.1, 8.2]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          coverage: xdebug
          extensions: soap
      - name: Install dependencies
        run: composer install
      - name: PHPUnit check
        run: ./vendor/bin/phpunit --coverage-text
